create table PRICES
(
    BRANDID   INTEGER,
    STARTDATE TIMESTAMP,
    ENDDATE   TIMESTAMP,
    PRICELIST INTEGER,
    PRODUCTID INTEGER,
    PRIORITY  INTEGER,
    PRICE     NUMERIC(20,2),
    CURR      CHARACTER VARYING
);

